[package]
name = "zfs_node"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
tokio = { version = "1.39.3", features = ["full"] }
tonic-reflection = "0.12.1"
zfs_protos = { path = "../zfs_protos" }

[build-dependencies]
tonic-build = "0.12.1"
